name: RaldiSystem
author: GunnableScum
api-version: 1.20
version: 1.1.2
main: de.gunnablescum.raldisystem.Main
commands:
  filedownload:
    description: Download Files remotely (Gunnable and Indying only)
  console:
    description: Execute a console command from ingame (Gunnable and Indying only)
  reloadconfig:
    description: Reloads the Config if changed. (OPs only)
  config:
    description: Change a parameter in the config (OPs only)