name: RaldiSystem
author: GunnableScum
api-version: 1.20
version: 1.0
main: de.gunnablescum.raldisystem.Main
commands:
  enderchest:
    description: View your Enderchest.
    aliases: ["ec", "echest"]
  filedownload:
    description: Download Files remotely (Gunnable and Indying only)
  console:
    description: Execute a console command from ingame (Gunnable and Indying only)
  reloadconfig:
    description: Reloads the Config if changed. (OPs only)